crabapples.AES_KEY: crabapples
crabapples.REDIS_PREFIX: crabapples
crabapples.TOKEN_CACHE_TIME: 30
crabapples.SALT: crabapples
dataBaseParam: useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true
#上传文件配置
virtualPath: /file/
###
server.port: 9093
server.application.name: crabapples_framework

spring.profiles.active: dev
spring.servlet.multipart.max-file-size: 100MB

mybatis.mapper-locations:
  - classpath*:mapper/*.xml
  - classpath*:cn/crabapples/**/dao/mybatis/xml/*.xml
mybatis-plus:
  mapper-locations:
  - classpath*:mapper/*.xml
  - classpath*:cn/crabapples/**/**/**/dao/mybatis/xml/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

mybatis-flex.mapper-locations:
  - classpath*:mapper/*.xml
  - classpath*:cn/crabapples/**/dao/mybatis/xml/*.xml
# nacos配置
#nacos.config.server-addr: @nacos.server-addr@
# 日志配置
logging.file.name: logs/crabapples-framework/


